default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: mvp-booster-rails_development

test:
  <<: *default
  database: mvp-booster-rails_test

production:
  <<: *default
  database: mvp-booster-rails_production
  username: mvp-booster-rails
